Repository LuaLS/LuaLS.github.io, pull requests merged in 2023-12, with the labels that each got.

#17 Upgrade to Astro 4
  package-lock.json
  package.json
  src/components/common/Accordion.astro
  src/components/common/CodeBlock.astro
  src/components/common/FileTreeItem.astro
  src/components/common/Loading.astro
  src/components/common/Remark.astro
  src/components/common/Tabs.astro
  src/components/layout/Header.astro
  src/components/wiki/Diagnostic.astro
  src/layouts/WikiArticle.astro
  src/pages/index.astro
Labels: dependencies

#18 fix: remove one of the duplicated footer in wiki articles
  src/layouts/WikiArticle.astro
Labels: bug

#19 --check usage tweaks
  src/content/wiki/usage.mdx
Labels: wiki/improvement
