Repository LuaLS/LuaLS.github.io, pull requests merged in 2024-04, with the labels that each got.

#33 Update deps
  package.json
  src/test/header.spec.ts
  src/test/index.spec.ts
  src/test/search.spec.ts
  src/test/wiki_article.spec.ts
  src/util/fetch.ts
Labels: dependencies

#34 refactor: use Astro image optimization
  docs/CONTRIBUTING-WIKI.md
  src/assets/images/json.svg
  src/assets/images/kakoune.svg
  src/assets/images/linux.svg
  src/assets/images/lua.svg
  src/assets/images/mac.svg
  src/assets/images/neovim.svg
  src/assets/images/user.svg
  src/assets/images/vscode.svg
  src/assets/images/wiki/annotation-snippet.png
  src/assets/images/windows.svg
  src/assets/images/wsl.svg
  src/components/common/Tabs.astro
  src/components/wiki/Image.astro
  src/components/wiki/README.md
  src/content/wiki/annotations.mdx
  src/content/wiki/build.mdx
  src/content/wiki/developing.mdx
  src/content/wiki/export-docs.mdx
  src/content/wiki/faq.mdx
  src/content/wiki/formatter.mdx
  src/content/wiki/usage.mdx
  src/pages/index.astro
  src/pages/wiki/[...slug].astro
  src/pages/wiki/index.astro
Labels: enhancement

#31 add: plugin ResolveRequire
  src/content/wiki/plugins.mdx
Labels: wiki/authoring
